# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('organizer', '0003_startup_data'),
    ]

    operations = [
    ]
