# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 15:44
from __future__ import unicode_literals

from django.db import migrations


def add_tag_data(apps, schema_editor):
    pass


def remove_tag_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
    ]
