# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_tag_data'),
    ]

    operations = [
    ]
